config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  
  get 'index' => 'main#index'

  get 'events' => 'main#events'

  get 'sponsorship' => 'main#sponsorship'

  get 'about-us' => 'main#about_us'

  get 'contact-us' => 'main#contact_us'

  get 'hsbc-womens-mentoring' => 'main#hsbc_womens_mentoring'

  get 'publications' => 'main#blog'
  get 'blog' => 'main#blog'
  get 'weeklywrap' => 'main#weeklywrap'
  get 'newsletter' => 'main#newsletter'
  get 'course-guide' => 'main#course_guide'

  get 'admin' => 'admin#index'

  post 'admin' => 'admin#check_login' 

	get 'control-panel' => 'admin#control_panel'

end

app/models/events.rb
class Events < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "finsoc2017"
	protect_from_forgery with: :exception
  include AdminHelper

  def index
		if session[:logged_in] == true
			redirect_to :action => "control_panel"
		end
  end

  def check_login
    if params[:session][:user] != "warrenbuffett" && params[:session][:user] != "edwardren"
			flash[:danger] = "Invalid"
      redirect_to :controller => "main", :action => "index"
    else
			log_in 'admin'
      redirect_to :action=> "control_panel"
    end
  end

	def control_panel
		if session[:logged_in] != true
			redirect_to :controller => "main", :action => "index"
		end
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # TODO Clean up show_new_page variable
    render "main/index", locals: { show_new_page: true }
  end

  def events
  end

  def sponsorship
    render "main/sponsorship", locals: { show_new_page: true }
  end

  def about_us
  end

  def newsletter
  end

  def contact_us
  end

  def publications
  end

  def course_guide
  end

  def hsbc_womens_mentoring
  end
  
  def weeklywrap
  end

  def weeklywrap
  end

  #def new
  #  render "main/index", locals: { show_new_page: true }
  #end

  #def newsponsors
  #  render "main/sponsorship", locals: { show_new_page: true }
  #end
end

app/helpers/admin_helper.rb
module AdminHelper
	
	# Session Login for Admin
	def log_in(user)
		session[:logged_in] = true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/control_panel.html.erb
<div class="control-panel-container container">
    <h1>Control panel</h1>
    <h2>Events Control</h2>
        <p>Events</p>
        <p>Add Event</p>
        <p>Edit Event</p>
        <p>Remove Event</p>
    <h2>Newsletter Control</h2>
</div>

app/views/admin/index.html.erb
<% provide(:title, "Admin") %>
<div class="admin-container container">
<h1>Admin Log In</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: admin_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :user, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container footerCentre">

	<div class="col-md-2 site-map">
		<h5>ABOUT US</h5>
		<%= link_to "Our Team", about_us_path(anchor: "team"), method: :get %>
		<%= link_to "Our Values", about_us_path(anchor: "values"), method: :get %>
        <%= link_to "Contact Us", contact_us_path(anchor: ""), method: :get %>
	</div>
	<div class="col-md-2 site-map">
		<h5>SPONSORS</h5>
		<%= link_to "Our Sponsors", sponsorship_path(anchor: "sponsors"), method: :get %>
		<%= link_to "Apply", sponsorship_path(anchor: "apply"), method: :get %>
        
	</div>
	<div class="col-md-2 site-map">
		<h5>EVENTS</h5>
		<%= link_to "Latest events", events_path(anchor: "upcoming"), method: :get %>
	</div>
    <div class="col-md-2 site-map">
		<h5>PUBLICATIONS</h5>
		<%= link_to "Newsletter", newsletter_path(anchor: ""), method: :get %>
        <%= link_to "Course Guide", course_guide_path(anchor: ""), method: :get %>
	    <%= link_to "Financial Articles", blog_path(anchor: ""), method: :get %>
	<%= link_to "Weekly Wrap", weeklywrap_path(anchor: ""), method: :get %>
	</div>
	<div class="col-md-3 social-media-box" id="contacts">
        <p>
            <a style="display:inline-block !important;" id="facebook-icon" href="https://www.facebook.com/FINSOCUNSW/" target="_blank">
                <i class="fa fa-facebook-square"></i>
            </a>
            <a style="display:inline-block !important;" id="linkedin-icon" href="https://au.linkedin.com/company/unsw-finance-and-banking-society" target="_blank">
                <i class="fa fa-linkedin-square"></i>
            </a> 
		</p>
        <p>
			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
			Kensington, New South Wales
		</p>
		<p>
			<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            <a style="" href='mailto:enquiries@unswfinsoc.org.au'>enquiries@unswfinsoc.org.au</a>
        </p>
        
       
	</div>
     
</div>

<div class="container">
    <div class="col-md-3">
        <p>&copy 2020 UNSW FINSOC </p>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="finsoc-navbar-div" class="navbar navbar-inverse navbar-fixed-top z-depth-1" role="navigation">
    <div class="container">
		  <div class="navbar-header">
	    	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar">
	        <span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
       		<span class="icon-bar"></span>
       		<span class="icon-bar"></span>
	    	</button>
			    <%= link_to image_tag("logo-min.png", id: "header-logo"), root_path, class: "navbar-brand", method: :get %>
		  </div>
		  <div id="top-navbar" class="navbar-collapse collapse">
		      <ul class="nav navbar-nav navbar-right">
						<li class="navbar-item"><%= link_to "Events", events_path, class:"navbar-item-link", method: :get %></li>
            <li class="navbar-item"><%= link_to "HSBC Mentor Program", hsbc_womens_mentoring_path, class:"navbar-item-link", method: :get %></li>
						<li class="navbar-item"><%= link_to "Sponsors", sponsorship_path, class:"navbar-item-link", method: :get %></li>
            <li class="navbar-item navbar-dropdown">
              <a class="dropdown-toggle navbar-item-link">
                About Us<span class="caret"></span>
                </a>
              <ul class="dropdown-menu">
                <li><%= link_to "About Us", about_us_path, method: :get %></li>
                <li><%= link_to "Contact Us", contact_us_path, method: :get %></li>
              </ul>
            </li>
            <li class="navbar-item navbar-dropdown">
              <%= link_to publications_path, class:"dropdown-toggle navbar-item-link", method: :get do %>
                Publications<span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to "Newsletter", newsletter_path, method: :get %></li>
                <li><%= link_to "Course Guide", course_guide_path, method: :get %></li>
		<li><%= link_to "Financial Articles", blog_path, method: :get %></li>
		<li><%= link_to "Weekly Wrap", weeklywrap_path, method: :get %></li>
              </ul>
            </li>
		      </ul>
		  </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155011925-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-155011925-1');
  </script>
  <meta id="vp" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale:1.0, user-scalable=0">
    <script>
    // Limited View Port Width
    if (screen.width < 304)
    {
        var mvp = document.getElementById('vp');
        mvp.setAttribute('content','width=304');
    }
    </script>

  <title>UNSW FINSOC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="finsoc-navbar">
    <%= render partial: "layouts/navbar" %>
  </div>
  <div id="wrapper">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <div id="footer" class="container">
      <%= render partial: "layouts/footer" %>
    </div>
  </div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96534836-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/main/blog.html.erb
<div class="PagePublications container">

  <div class="title">
    <h1>BLOG</h1>
  </div>
  <div class="Card">
    <div class="Card-text">
      <h3 style="font-size:27px;">Recent Articles</h3> 
    </div>
    <div class="Card-footer Card-footer--right">
        <%= link_to newsletter_path, method: :get do%>
          
        <% end %>
    </div>
    <iframe src="https://drive.google.com/file/d/13rXFiJtLBAVifyuTxXRdZgycJsFVCm75/preview" width="840" height="480"></iframe>
    <iframe src="https://drive.google.com/file/d/1WX_kKeEw4OELAemFmoqGYSxUsD2HQNvX/preview" width="840" height="480"></iframe>
    <iframe src="https://drive.google.com/file/d/1mQ5dUuvKvYDhK43Gf_e1O75--Z9aO7Zf/preview" width="840" height="480"></iframe>
    <iframe src="https://drive.google.com/file/d/1W0SU-N7qSSTCrK857FI7A9TpuUCBulLb/preview" width="840" height="480"></iframe>
</div>

app/views/main/contact_us.html.erb
<div class="pageContactUs">
    <div class = "contactHeader">
        <div class="container">
            <div class="title1">
                <br/>
                <h1> Contact Us</h1>
            </div>
        </div>
    </div>
    
    <div class="section2">
        <br/><br/>
        <div class="container">
            <div class="contact-us-container row">
                <div class="col-md-8">
                    <iframe width="100%" height="500px" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=unsw&key=AIzaSyDBxcJiZSxocnv-8DR_PlBo2gnubvaQwIA" allowfullscreen></iframe>
                </div>
                <div height="500px" class="contact-us-content col-md-4">
                    <br/>
                    <i class="fa fa-envelope large-icon"></i>
                    <div>
                      <p>Contact us via:
                      <p class="finsoc-email"><a style="" href='mailto:enquiries@unswfinsoc.org.au'>enquiries@unswfinsoc.org.au</a></p>
                        <p>For individual emails refer to team <b><span class="bioLink"><%= link_to "BIOS", about_us_path(anchor: "team"), method: :get %></span></b></p>
                      <br>
                      <p>OR</p>
                      <br>
                      <p>for website-related queries:</p>
                      <p class="finsoc-email"><a style="" href='mailto:it@unswfinsoc.org.au'>it@unswfinsoc.org.au</a></p>
                      <p>
                    </div>

                    <div class="social-media-box col-md-12">
                      <div>
                        Follow us on:
                      </div>
                      <br>
                      <a id="facebook-icon" href="https://www.facebook.com/FINSOCUNSW/" target="_blank">
                        <i class="fa fa-facebook"></i>
                      </a>

                      <a id="linkedin-icon" href="https://au.linkedin.com/company/unsw-finance-and-banking-society"  target="_blank">
                        <i class="fa fa-linkedin"></i>
                      </a>
                    </div>
                </div>
                <br/><br/><br/>
            </div>
        </div>
    </div>
</div>

app/views/main/hsbc_womens_mentoring.html.erb
<div class="PageHSBCMentor">
  <a name="values"></a> 
    <div class = "aboutHeader">
        <div class="container">
    <div class="title1">
        <br/>
        <h1>Women in Finance</h1>
    </div>
    </div>
</div>
    
    <div class="content">
    <div class="section">
      <div class="section-text container">
        <div class="subheading">
          <h2 class="h2Custom">What is it?</h2>
            <br/>
        </div>
          <span class="FinsocHighlight">To help Business Students with an interest in Banking and Financial Planning in achieving their career objectives within the Financial services industry.</span><br/><br/>
        <p class="PageHSBCMentor-text">
            The HSBC Women in Finance Mentoring Program is an annual mentoring program hosted in partnership with HSBC, to connect current female finance students with successful finance industry professionals. The program aims to provide an opportunity for female finance students to develop a close relationship and receive guidance from experienced and accomplished professionals, in planning and navigating a successful career in the finance industry.
            </p>
            <p class="PageHSBCMentor-text">
                Students can gain valuable insight into what it is like in the finance professional and gain a lifelong mentor/friend to whom they can turn to, on not only professional issues and concerns, but also more personal problems in relation to working in a heavily male-dominated finance industry as a woman.
            </p>
      </div>
    </div>
    <div class="section2">
    <div class="section2">
      <div class="section-text container">
        <div class="subheading">
           <h2 class="h2Custom">Sponsors on Board</h2>
            <br/>
        </div>
  
	      <%= render partial: "main/sponsors/template", locals: {
        id: "HSBC",
        name: "HSBC",
        image_file: "hsbc3.png",
        detail: "",
        site_url: "https://www.hsbc.com.au/"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "Challenger",
        name: "Challenger",
        image_file: "challenger.png",
        detail: "",
        site_url: "https://www.challenger.com.au/about-us"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "shadforth",
        name: "Shadforth",
        image_file: "shadforth.jpg",
        detail: "",
        site_url: "https://www.sfg.com.au/"
      }%>
	         <%= render partial: "main/sponsors/template", locals: {
        id: "cfm",
        name: "CFM",
        image_file: "cfm.png",
        detail: "",
        site_url: "https://cfmaltbeta.com.au/"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "bain",
        name: "Bain",
        image_file: "bain.png",
        detail: "",
        site_url: "https://www.bain.com/"
      }%>
	       <%= render partial: "main/sponsors/template", locals: {
        id: "lazard",
        name: "Lazard",
        image_file: "lazard.png",
        detail: "",
        site_url: "https://www.lazard.com/"
      }%>
	       <%= render partial: "main/sponsors/template", locals: {
        id: "amp",
        name: "AMP Capital",
        image_file: "amp.jpg",
        detail: "",
        site_url: "https://www.ampcapital.com/au/en/home"
      }%>	      
	       <%= render partial: "main/sponsors/template", locals: {
        id: "wibf",
        name: "WIBF",
        image_file: "wibf.png",
        detail: "",
        site_url: "https://www.wibf.org.au/press-kit/"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "cba",
        name: "Commonwealth Bank",
        image_file: "commbank.jpg",
        detail: "",
        site_url: "https://www.commbank.com.au/"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "ey",
        name: "EY",
        image_file: "ey.png",
        detail: "",
        site_url: "https://www.ey.com/en_au"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "franklin",
        name: "Franklin Templeton",
        image_file: "Franklin.jpg",
        detail: "",
        site_url: "https://www.franklintempleton.com.au/"
      }%>
	     <%= render partial: "main/sponsors/template", locals: {
        id: "palisade",
        name: "Palisade Investment",
        image_file: "palisade.png",
        detail: "",
        site_url: "https://palisadepartners.com.au/"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "citi",
        name: "CitiBank",
        image_file: "citi.png",
        detail: "",
        site_url: "https://www1.citibank.com.au"
      }%>
	      <%= render partial: "main/sponsors/template", locals: {
        id: "westpac",
        name: "Westpac",
        image_file: "westpac.png",
        detail: "",
        site_url: "https://www.westpac.com.au/"
      }%>
	      
	      
	      
	  
	    
	    
	      
	      
	     
	      
	    
   
      </div>
    </div>
    </div>
        
    <div class="section">
      <div class="section-text container">
        <div class="subheading">
          <h2 class="h2Custom">Who are we looking for?</h2>
            <br/>
        </div>
          <span class="FinsocHighlight"><center>We are looking for female identifying UNSW finance students who are ambitious and driven!</center></span><br/><br/>
      </div>
    </div>    
    
    
    <div class="section">
      <div class="section-text container">
        <div class="subheading">
          <h2 class="h2Custom">How do I apply?</h2>
            <br/>
        </div>
            <p class="PageHSBCMentor-text">
                <center>This is a 6 month commitment and therefore we cannot accept those going on exchange.</center>
            </p>   

             <p class="PageHSBCMentor-text">

                 <center>Applications are ROLLING and close 11:59pm 13th March, with interviews being undertaken early the week after!  </center>      </p>
             <p class="PageHSBCMentor-text">

                 <center>If you have any questions please do not hesitate to contact Christina Kim, General Secretary, at secretary@unswfinsoc.org.au.       </center>     </p>
          <hr/>
<a href="https://docs.google.com/forms/d/e/1FAIpQLScXe2wCjvLl9mrCBzqACxTG4k8YpAL1odR5IwCJQfQH9RaEgQ/viewform">
        <div class="Card-footer Card-footer--center">
            <center><button class="Link"  type="button">APPLICATIONS OPEN</button></center>
            </div>
		</a>
        
        </div>
        </div>

    </div>
    
    <div class="container">
        
        
        
        
    </div>
</div>

app/views/main/index.html.erb
<div class="PageIndex">

    

    <div id="finsoc-banner">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
              </ol>
          <div class="carousel-inner" role="listbox">
           <div class="item active carousel-img PageIndex-carousel-img">
              <div class="PageIndex-carousel-text">
                <h1>
                  Finance & Banking Society
                </h1>
                <h2>
                  University of New South Wales<br/>
                  FINSOC
                </h2>
              </div>
              <% if  show_new_page %>

                  <a href="https://forms.gle/juvmQfF133dMwpiU8" target="_blank"><div class="event-box">
                      <!--<b>UPCOMING EVENTS</b>-->
                      <b class="darkButton">2020 SIGN UP &rarr; </b>
                      </div></a>
              <% end %>
             <%= image_tag "events/default-min-2.jpg", id:"finsoc-banner-logo", alt: "UNSW FINSOC" %>
          </div>
              <div class="item carousel-img PageIndex-carousel-img">
              <div class="PageIndex-carousel-text">
                <h1>
                  Get involved with FINSOC!
                </h1>
                <h2>
                  Join our <a href="http://eepurl.com/bQ0Pmv" target="_blank"><b>Mailing List </b></a> and follow us on <a href="https://www.facebook.com/FINSOCUNSW/" target="_blank"><b>Facebook </b></a><br/>
                  
                </h2>
              </div>
              <% if  show_new_page %>

                  <a href="https://docs.google.com/forms/d/e/1FAIpQLSe46D9iy8aW_9PahduBjQhqGZJThfEG7h3szb49ThEssaoZww/viewform" target="_blank"><div class="event-box">
                      <!--<b>UPCOMING EVENTS</b>-->
                      <b>Sign up for FINSOC &rarr; </b>
                      </div></a>
              <% end %>
             <%= image_tag "team.png", id:"finsoc-banner-logo", alt: "UNSW FINSOC" %>
           </div>
          </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
        </div>
    </div>

    <div class="PageIndex-featured container">
      <%= link_to course_guide_path, :class=> "PageIndex-courseGuideFeature", method: :get do %>
            <div class="PageIndex-courseGuideFeature-text">
              <p>View our</p>
              <p>Finance Course Guide</p>
             <span class="glyphicon glyphicon-info-sign PageIndex-courseGuideFeature-icon" aria-hidden="true"></span> 
            </div>
        <% end %>
        <div class="Event">
            <%= link_to events_path, method: :get do %>

            <div class="Event-imgContainer">
                  <div class="Event-imgContainer-link">
                      <%= image_tag "events/2018/advice.jpg", :class=> "Event-imgContainer-img Event-imgContainer-img--showRight", alt: "Investment Advice" %>
                  </div>
            </div>
            <% end %>
            <div class="Event-title">
            Investment Advice

            </div>
        </div>
        <div class="Event Event-past">
            <%= link_to events_path, method: :get do %>

            <div class="Event-imgContainer">
                    <%= image_tag "events/2018/ey_case.jpg", :class=> "Event-imgContainer-img", alt: "EY Case Comp" %>
            </div>
            <% end %>
            <div class="Event-title">
            EY Case Comp
            </div>
        </div>
        <div class="Event Event-past">
            <%= link_to events_path, method: :get do %>

            <div class="Event-imgContainer">
                    <%= image_tag "events/2018/games.jpg", :class=> "Event-imgContainer-img", alt: "Games Night" %>
            </div>
            <% end %>
            <div class="Event-title">
            Games Night
            </div>
        </div>
        
        
    </div>
    <div class="section2">
      <div class="section-text container" style="padding-bottom:0px;">
        <div class="Card PageIndex-missionCard">
            <div class="title">
                <h2>Our Mission</h2>
            </div>
            <div class="PageIndex-missionCard-text">
                <p>To become Australia&#8217;s leading student run society platform in assisting students on achieving their banking and financial planning career goals.</p>
            </div>
        </div>
      </div>
    </div>
    <div class="section2 filler">
      <div class="container">
    
      </div>
    </div>
     <div class="section">
      <div class="section-text container">
        <div class="">
          <div class="Card-text">
              <br/>
              <br/>
            <div class="title">
              <h2>Our Sponsors</h2>
                <br/>
                <br/>
            </div>
            <% if !show_new_page %>
            <div class="SponsorsList"> 
              <div class="SponsorsList-item">
                  <%= image_tag "sponsors/fpa.jpg", alt: "FPA" %>
              </div>
              <div class="SponsorsList-item">
              <%= image_tag "sponsors/gradmentor.jpg", alt: "GradMentor" %>
              </div>
              <div class="SponsorsList-item">
              <%= image_tag "sponsors/logozookal.png", alt: "Zookal" %>
              </div>
            </div>
          <% end %>
            <% if show_new_page %>
            <div class="SponsorsList"> 
              <div class="SponsorsList-item SponsorsList-hsbc">
                  <%= image_tag "sponsors/hsbc3.png", alt: "HSBC" %>
              </div>
              <div class="SponsorsList-item">
                  <%= image_tag "sponsors/cfa.jpg", alt: "CFA Institute" %>
              </div>
              <div class="SponsorsList-item SponsorsList-hsbc">
                  <%= image_tag "sponsors/challenger-logo.png", alt: "Challenger" %>
              </div>
              
            </div>
            <div class="SponsorsList">
              <div class="SponsorsList-item">
                  <%= image_tag "sponsors/Franklin.jpg", alt: "Franklin Templeton Investments" %>
              </div>
              <div class="SponsorsList-item SponsorsList-wilsons">
                  <%= image_tag "sponsors/investec.png", alt: "Investec" %>
              </div>
              <div class="SponsorsList-item">
                  <%= image_tag "sponsors/cfm.png", alt: "CFM" %>
              </div>
              
            </div>
            <div class="SponsorsList">
              <div class="SponsorsList-item">
                  <%= image_tag "sponsors/westpac.png", alt: "Westpac" %>
              </div>
              <div class="SponsorsList-item SponsorsList-gresham">
                  <%= image_tag "sponsors/ey.png", alt: "EY" %>
              </div>
                <div class="SponsorsList-item SponsorsList-zookal">
                  <%= image_tag "sponsors/bain.png", alt: "Bain" %>
              </div>
              <div class="SponsorsList-item SponsorsList-aima">
                  <%= image_tag "sponsors/fpa.png", alt: "FPA" %>
              </div>
            </div>
            <div class="SponsorsList">
                <div class="SponsorsList-item">
                  <%= image_tag "sponsors/amp.jpg", alt: "AMP Capital" %>
              </div>
              <div class="SponsorsList-item SponsorsList-luminis">
                  <%= image_tag "sponsors/palisade.png", alt: "Palisade Investment Partners" %>
              </div>
              <div class="SponsorsList-item SponsorsList-aima">
                  <%= image_tag "sponsors/ft.png", alt: "Flow Traders" %>
              </div>
                <div class="SponsorsList-item SponsorsList-luminis">
                  <%= image_tag "sponsors/wibf.png", alt: "WIBF" %>
              </div>
                
            </div>
          <% end %>
          </div>
            <br/>
            <hr/>
            <br/>
            <center>
              <div class="Card-footer Card-footer--center">
                <%= link_to sponsorship_path, method: :get do %>
                    <button class="Link">
                        More Details
                    </button>
                <% end %>
              </div>
            </center>
        </div>
      </div>
    </div>    


</div>

app/views/main/newsletter.html.erb
<div class="newsletter-container container">
  <div class="title">
    <h1>NEWSLETTER</h1>
  </div>

  <iframe id="newsletter" src="http://sh1.sendinblue.com/2n43gyb91t7e.html?t=1587555937">
    <p>Your browser does not support iframes.</p>
  </iframe>
</div>

app/views/main/sponsors/_template.html.erb
<a class="cardLink" target="_blank" href="<%= site_url %>">
    <div id="<%= id %>" class="SponsorTile <% if detail == "" %>SponsorTile--noDetail<% end %>">
      <div class="SponsorTile-imgContainer">
        <%= image_tag "sponsors/"+image_file %>
      </div>
      <div class="SponsorTile-text">
        <div class="SponsorTile-text-title"><h1 class="display-4"><%= name %></h1></div>
        <div class="SponsorTile-text-content" data-content>
          <%= detail %>
        </div>
        <div class="SponsorTile-text-footer">
          <a class="SponsorTile-text-footer-link" href="<%= site_url %>">Visit Site</a>
          <span class="SponsorTile-text-footer-arrow glyphicon glyphicon-chevron-down"
                aria-hidden="true" data-arrow="<%= id %>-arrow"></span>
        </div>
      </div>
    </div>
</a>